# Clés du projet SonarCloud
sonar.organization=noorzaghouani
sonar.projectKey=noorzaghouani_MediConnect-
sonar.sources=src,templates,public,assets,config
sonar.tests=tests

# Exclure les dossiers générés et fichiers de squelette
sonar.exclusions=var/**,vendor/**,public/bundles/**,migrations/**,assets/controllers/hello_controller.js

# Désactiver l'exigence de couverture de tests unitaires (Coverage)
sonar.coverage.exclusions=**

# Exclusions de duplication
sonar.cpd.exclusions=migrations/**,tests/**

# Définir l'encodage
sonar.sourceEncoding=UTF-8
