name: Security Pipeline - MediConnect

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  secrets-scan:
    name: Gitleaks - Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sast-scan:
    name: Semgrep - SAST Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: semgrep/semgrep-action@v1
        with:
          config: >-
            p/php
            p/owasp-top-ten

  sca-scan:
    name: Composer Audit - SCA Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
      - run: composer install --no-interaction --no-progress --prefer-dist
      - run: composer audit
        continue-on-error: true